Task 4 added mongo, passport
555java/master-project pull request #3
Opened 2022-11-01 07:32 UTC by 555java

2022-11-01 12:58 UTC, shredor requested changes

2022-11-01 12:58 UTC, shredor commented on backend-project/index.js
> +app.use(express.static("public"));
а зачем это? у нас же ничего не раздается из public/

2022-11-01 12:58 UTC, shredor commented on backend-project/index.js
> +  session({
Надо добавить хранение сессий в БД, например монго https://www.npmjs.com/package/connect-mongo
Иначе сессии будут пропадать при перезапуске проекта

2022-11-01 12:58 UTC, shredor commented on backend-project/package.json
> +    "bcryptjs": "^2.4.3",
Почему удалился express? Не вижу, bcrypt где-то используется, может его удалить?

2022-11-01 12:58 UTC, shredor commented on backend-project/src/route/userRoute.js
> +    res.json({ success: false, message: "Username was not given" });
тут можно добавить дефолтный обработчик ошибок https://expressjs.com/en/guide/error-handling.html
Типа такого
`next({ status: 400, message: '...' })`
`app.use((err,req,res,next) => { res.status(err.status).json({ isSuccess: false, message: err.message }) })`

2022-11-01 12:58 UTC, shredor commented on backend-project/src/route/userRoute.js
> +// const strategy = new LocalStrategy(function verify(username, password, cb) {
удалить?

2022-11-01 13:09 UTC, 555java commented on backend-project/index.js
> +  session({
ниже есть использование passport.session, но там есть какая то несовместимость и нужно обьявить просто session перед этим

2022-11-01 13:11 UTC, 555java commented on backend-project/package.json
> +    "bcryptjs": "^2.4.3",
у меня вот так `"dependencies": {
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.20.1",
    "cookie-parser": "^1.4.6",
    "express": "^4.18.2",
    "express-session": "^1.17.3",
    "mongoose": "^6.7.0",
    "passport": "^0.6.0",
    "passport-local": "^1.0.0",
    "passport-local-mongoose": "^7.1.2"
  },
  "devDependencies": {
    "nodemon": "^2.0.20"
  }`

2022-11-01 13:22 UTC, shredor commented on backend-project/index.js
> +  session({
Да, все правильно, только нужно добавить опцию, чтобы сессии хранились в монге (по моей ссылке пакет, который это помогает сделать)
```
import MongoStore from 'connect-mongo'

app.use(session({
  ........
  store: MongoStore.create(options)
}));```

2022-11-01 13:24 UTC, shredor commented on backend-project/package.json
> +    "bcryptjs": "^2.4.3",
А, сорри, вижу express. 
А bcrypt точно нужен? Не вижу, чтоб он импортился где-то

2022-11-02 10:35 UTC, 555java reviewed
All changes were talked

2022-11-02 10:35 UTC, merged